Pandas-DataFrame的创建、属性和方法

In [1]:
#导入NumPy包
import numpy as np
#导入Pandas包
import pandas as pd

'''
Pandas是Panel data analysis（面板数据分析）的缩写。
Pandas结合了NumPy和Matplotlib的功能，并且具有自己独特的数据结构。
'''

'\nPandas是Panel data analysis（面板数据分析）的缩写。\nPandas结合了NumPy和Matplotlib的功能，并且具有自己独特的数据结构。\n'

In [2]:
'''
Pandas的数据结构有Series，DataFrame和Panel（已移除）,其中最常用的是DataFrame。
DataFrame是既有行索引，又有列索引的二维数组。
'''

#用NumPy数组创建DataFrame
stock_change=np.random.normal(0,1,(10,5))
df1=pd.DataFrame(stock_change)
print(df1)

          0         1         2         3         4
0 -0.127355 -1.083297  0.514204 -0.287575  0.879042
1  0.298783  1.191097  1.129816  0.769241  0.340036
2  0.862758  0.087160  0.868918 -0.692609 -0.288216
3  0.912597  0.988065 -0.103838 -1.983208 -0.218940
4  1.143041 -1.654296 -0.121245 -0.335038 -0.702467
5  1.345215 -1.213683 -0.938890  0.935491 -0.826003
6 -0.264742 -0.793990  1.105911  1.619856 -0.041330
7 -1.301555  0.301695  3.115799  0.437936  0.409907
8 -0.114075 -0.083884 -0.290575 -0.963235  0.821605
9 -0.130846  0.425263 -0.542089  0.616700 -1.210358


In [3]:
#添加行索引
stock=['股票{}'.format(i) for i in range(10)]
df2=pd.DataFrame(stock_change,index=stock)
print(df2)

'''
注意：如果用一个DataFrame创建另一个DataFrame，那么创建的DataFrame所有元素为缺失值。
'''

            0         1         2         3         4
股票0 -0.127355 -1.083297  0.514204 -0.287575  0.879042
股票1  0.298783  1.191097  1.129816  0.769241  0.340036
股票2  0.862758  0.087160  0.868918 -0.692609 -0.288216
股票3  0.912597  0.988065 -0.103838 -1.983208 -0.218940
股票4  1.143041 -1.654296 -0.121245 -0.335038 -0.702467
股票5  1.345215 -1.213683 -0.938890  0.935491 -0.826003
股票6 -0.264742 -0.793990  1.105911  1.619856 -0.041330
股票7 -1.301555  0.301695  3.115799  0.437936  0.409907
股票8 -0.114075 -0.083884 -0.290575 -0.963235  0.821605
股票9 -0.130846  0.425263 -0.542089  0.616700 -1.210358


'\n注意：如果用一个DataFrame创建另一个DataFrame，那么创建的DataFrame所有元素为缺失值。\n'

In [4]:
#pd.date_range()
date=pd.date_range(start='20180101', periods=5, freq='B')
'''
pd.date_range()的参数：
（1）start：起始时间；
（2）end：结束时间；
（3）periods：期数；
（注意：start、end和periods这3个参数至少应该设置2个）
（4）freq：频率，常见取值如下：
①交易日频率：B；
②日历日频率：D；
③周频率：W；
④季度频率：Q；
⑤年频率：A,Y。
'''

#添加列索引
df3=pd.DataFrame(stock_change,index=stock,columns=date)
print(df3)

     2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05
股票0   -0.127355   -1.083297    0.514204   -0.287575    0.879042
股票1    0.298783    1.191097    1.129816    0.769241    0.340036
股票2    0.862758    0.087160    0.868918   -0.692609   -0.288216
股票3    0.912597    0.988065   -0.103838   -1.983208   -0.218940
股票4    1.143041   -1.654296   -0.121245   -0.335038   -0.702467
股票5    1.345215   -1.213683   -0.938890    0.935491   -0.826003
股票6   -0.264742   -0.793990    1.105911    1.619856   -0.041330
股票7   -1.301555    0.301695    3.115799    0.437936    0.409907
股票8   -0.114075   -0.083884   -0.290575   -0.963235    0.821605
股票9   -0.130846    0.425263   -0.542089    0.616700   -1.210358


In [5]:
#DataFrame的属性

#形状
print(df3.shape)
#行索引
print(df3.index)
#列索引
print(df3.columns)
#值（ndarray）
print(df3.values)

(10, 5)
Index(['股票0', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9'], dtype='object')
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='B')
[[-0.12735526 -1.08329652  0.51420415 -0.28757492  0.87904172]
 [ 0.298783    1.19109712  1.12981575  0.76924087  0.34003581]
 [ 0.8627582   0.08715964  0.86891843 -0.6926095  -0.28821605]
 [ 0.91259663  0.98806517 -0.10383807 -1.9832083  -0.21893952]
 [ 1.14304133 -1.65429564 -0.12124475 -0.33503849 -0.70246652]
 [ 1.34521489 -1.21368299 -0.93889019  0.93549065 -0.82600275]
 [-0.26474155 -0.79398969  1.10591055  1.61985584 -0.04133022]
 [-1.30155466  0.3016953   3.11579934  0.43793582  0.40990708]
 [-0.11407494 -0.08388415 -0.29057522 -0.96323519  0.82160498]
 [-0.13084629  0.42526335 -0.5420889   0.61670036 -1.21035768]]


In [6]:
#DataFrame的转置
df3.T

股票0       股票1       股票2       股票3       股票4       股票5  \
2018-01-01 -0.127355  0.298783  0.862758  0.912597  1.143041  1.345215   
2018-01-02 -1.083297  1.191097  0.087160  0.988065 -1.654296 -1.213683   
2018-01-03  0.514204  1.129816  0.868918 -0.103838 -0.121245 -0.938890   
2018-01-04 -0.287575  0.769241 -0.692609 -1.983208 -0.335038  0.935491   
2018-01-05  0.879042  0.340036 -0.288216 -0.218940 -0.702467 -0.826003   

                 股票6       股票7       股票8       股票9  
2018-01-01 -0.264742 -1.301555 -0.114075 -0.130846  
2018-01-02 -0.793990  0.301695 -0.083884  0.425263  
2018-01-03  1.105911  3.115799 -0.290575 -0.542089  
2018-01-04  1.619856  0.437936 -0.963235  0.616700  
2018-01-05 -0.041330  0.409907  0.821605 -1.210358

In [7]:
#取前若干行
print(df3.head(3))
#取后若干行
print(df3.tail(3))

     2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05
股票0   -0.127355   -1.083297    0.514204   -0.287575    0.879042
股票1    0.298783    1.191097    1.129816    0.769241    0.340036
股票2    0.862758    0.087160    0.868918   -0.692609   -0.288216
     2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05
股票7   -1.301555    0.301695    3.115799    0.437936    0.409907
股票8   -0.114075   -0.083884   -0.290575   -0.963235    0.821605
股票9   -0.130846    0.425263   -0.542089    0.616700   -1.210358
